[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "my_package"
version = "0.1"
dependencies = []

[project.scripts]
greet = "my_package.my_script:greet"
